### ISSUE TITLE
Vitashell Download error

### ISSUE THREAD

**Issue by zeroleo** [noahc3/auto-h-encore#29]
After install HENkaku, when i try download Vitashell, I received this message: 
Failed! 0x80431084

PS Vita 3.65

**Comment by fyr77** [comment]
Best see https://gbatemp.net/threads/h-encore-vitashell-error-0x80436003.509803/

This should be an issue with the hack itself, not auto-h-encore.

**Comment by fyr77** [comment]
It‘d be best if you asked this question on https://reddit.com/r/vitahacks as well, since this should be an issue with the hack itself, not auto-h-encore. Maybe see this thread on gbatemp, it‘s a different error but maybe it will work for you: https://gbatemp.net/threads/h-encore-vitashell-error-0x80436003.509803/

**Comment by noahc3** [comment]
Make sure airplane mode is off and wifi is connected. This is some kind of HTTP error code so VitaShell is failing to download because of the internet for some reason.

**Comment by noahc3** [comment]
Closing this as unrelated as this is a problem with h-encore itself. Try /r/vitahacks as fyr77 suggested, or the vita hacks discord.
