### ISSUE TITLE
malwarebyte identify the app as a malware

### ISSUE THREAD

**Issue by wababc** [noahc3/auto-h-encore#57]
as the title say it . here's a capture of that  
![malwarealert](https://user-images.githubusercontent.com/36303163/42527060-e62e34b2-8477-11e8-87dd-1278be0e3a2b.JPG)

**Comment by noahc3** [comment]
This is their machine learning picking it up as a safety net, but it doesn't actually verify that any malware exists.

I'm pretty sure what is tripping it off is how I'm doing multi-language support since MB started throwing false positives when I added that, but I don't really have any way around it for now.

To be clear, [VirusTotal has no problems](https://www.virustotal.com/#/file/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855/detection), and anyone could just open the program it dotpeek or something if they are skeptical.
